### ISSUE TITLE
2.16.0 ReferenceError: lib is not defined

### ISSUE THREAD

**Issue by resentment-industries** [upload-io/upload-javascript-sdk#3]
Versions 2.16.0 and above, i'm receiving this error

ReferenceError: lib is not defined
    at /node_modules/upload-js-full/dist/node/cjs/main.js:3703:1
    at Object.<anonymous> (/node_modules/upload-js-full/dist/node/cjs/main.js:3704:12)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at Module.Hook._require.Module.require (/Users/dev/.nvm/versions/node/v16.19.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/services/UploadService.js:2:16)
    
node: '19.9.0',

**Comment by ljwagerfield** [comment]
Fixed in `2.21.0`, thank you for raising!
